In [56]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus', 'html.parser')
response = requests.get(url)
response

In [59]:
markup = response.text
xml_code = BeautifulSoup(markup, "lxml")
table_code = xml_code.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>36,453,355</td>
<td>+6,220</td>
<td>830,580</td>
<td>+616</td>
<td>28,198,807</td>
<td>+4,077</td>
<td>7,423,968</td>
<td>15,949</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>21,956,794</td>
<td>+1,076</td>
<td>577,701</td>
<td>+19</td>
<td>19,677,486</td>
<td>+1,025</td>
<td>1,701,607</td>
<td>21,618</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>30,113,540</td>
<td>+56,940</td>
<td>440,579</td>
<td>+596</td>
<td>27,089,485</td>
<td>+31,400</td>
<td>2,583,476</td>
<td>27,248</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>40,910,057</td>
<td>+89,916</td>
<td>939,293</td>
<td>+2,552</td>
<td>29,025,119</td>
<td>+73,502</td>
<td>10,945,645</td>
<td>32,919</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>4,337,649</td>
<td>+1,022</td>
<td>114,907</td>
<td>+30</td>
<td>3,886,712</td>
<td>+746</td>
<td>336,030</td>
<td>3,238</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>58,861</td>
<td>+35</td>
<td>1,151</td>
<td>+1</td>
<td>34,640</td>
<td>+12</td>
<td>23,070</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>133,830,977</td>
<td>+155,209</td>
<td>2,904,226</td>
<td>+3,814</td>
<td>107,912,955</td>
<td>+110,762</td>
<td>23,013,796</td>
<td>100,977</td>
<td>17,169</td>
<td>372.6</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">31,637,243</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">572,849 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">24,206,539</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">6,857,855</td>
<td style="font-weight: bold; text-align:right">9,058</td>
<td style="font-weight: bold; text-align:right">95,153</td>
<td style="font-weight: bold; text-align:right">1,723</td>
<td style="font-weight: bold; text-align:right">413,478,674</td>
<td style="font-weight: bold; text-align:right">1,243,583</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,489,703</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>11</td><td>580</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">13,197,031</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">341,097 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">11,664,158</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,191,776</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">61,750</td>
<td style="font-weight: bold; text-align:right">1,596</td>
<td style="font-weight: bold; text-align:right">28,600,000</td>
<td style="font-weight: bold; text-align:right">133,822</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,716,460</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>16</td><td>627</td><td>7</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">12,928,574</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,513</td>
<td style="font-weight: bold; text-align:right;">166,892 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">11,851,393</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,488</td>
<td style="text-align:right;font-weight:bold;">910,289</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">9,299</td>
<td style="font-weight: bold; text-align:right">120</td>
<td style="font-weight: bold; text-align:right">252,677,379</td>
<td style="font-weight: bold; text-align:right">181,732</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,390,382,831</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>108</td><td>8,331</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">4,841,308</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">97,722 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">301,299</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">4,442,287</td>
<td style="font-weight: bold; text-align:right">5,626</td>
<td style="font-weight: bold; text-align:right">74,044</td>
<td style="font-weight: bold; text-align:right">1,495</td>
<td style="font-weight: bold; text-align:right">67,791,157</td>
<td style="font-weight: bold; text-align:right">1,036,811</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,384,318</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>14</td><td>669</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">4,614,834</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,672</td>
<td style="font-weight: bold; text-align:right;">101,845 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+365</td>
<td style="font-weight: bold; text-align:right">4,239,038</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,558</td>
<td style="text-align:right;font-weight:bold;">273,951</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">31,612</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">122,600,000</td>
<td style="font-weight: bold; text-align:right">839,827</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,982,499</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>32</td><td>1,433</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">4,367,291</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">126,927 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,932,777</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">307,587</td>
<td style="font-weight: bold; text-align:right">469</td>
<td style="font-weight: bold; text-align:right">64,075</td>
<td style="font-weight: bold; text-align:right">1,862</td>
<td style="font-weight: bold; text-align:right">132,141,580</td>
<td style="font-weight: bold; text-align:right">1,938,717</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,159,282</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>16</td><td>537</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">3,700,393</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">112,374 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,040,182</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">547,837</td>
<td style="font-weight: bold; text-align:right">3,683</td>
<td style="font-weight: bold; text-align:right">61,271</td>
<td style="font-weight: bold; text-align:right">1,861</td>
<td style="font-weight: bold; text-align:right">51,755,739</td>
<td style="font-weight: bold; text-align:right">856,975</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,393,531</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>16</td><td>537</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">3,633,925</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">32,943 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,194,978</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">406,004</td>
<td style="font-weight: bold; text-align:right">2,604</td>
<td style="font-weight: bold; text-align:right">42,735</td>
<td style="font-weight: bold; text-align:right">387</td>
<td style="font-weight: bold; text-align:right">40,385,250</td>
<td style="font-weight: bold; text-align:right">474,936</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,033,013</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>23</td><td>2,581</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">3,326,736</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">76,037 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,085,059</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">165,640</td>
<td style="font-weight: bold; text-align:right">2,009</td>
<td style="font-weight: bold; text-align:right">71,132</td>
<td style="font-weight: bold; text-align:right">1,626</td>
<td style="font-weight: bold; text-align:right">43,458,915</td>
<td style="font-weight: bold; text-align:right">929,231</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,768,680</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>14</td><td>615</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">2,927,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">78,174 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,631,400</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+16,900</td>
<td style="text-align:right;font-weight:bold;">217,998</td>
<td style="font-weight: bold; text-align:right">4,439</td>
<td style="font-weight: bold; text-align:right">34,856</td>
<td style="font-weight: bold; text-align:right">931</td>
<td style="font-weight: bold; text-align:right">51,559,277</td>
<td style="font-weight: bold; text-align:right">613,878</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,989,395</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>29</td><td>1,074</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/poland/">Poland</a></td>
<td style="font-weight: bold; text-align:right">2,499,507</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+27,887</td>
<td style="font-weight: bold; text-align:right;">56,659 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+954</td>
<td style="font-weight: bold; text-align:right">2,076,504</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+21,807</td>
<td style="text-align:right;font-weight:bold;">366,344</td>
<td style="font-weight: bold; text-align:right">3,362</td>
<td style="font-weight: bold; text-align:right">66,099</td>
<td style="font-weight: bold; text-align:right">1,498</td>
<td style="font-weight: bold; text-align:right">12,700,278</td>
<td style="font-weight: bold; text-align:right">335,855</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/poland-population/">37,814,773</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>15</td><td>667</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
<td style="font-weight: bold; text-align:right">2,479,617</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">64,767 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,345,471</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">69,379</td>
<td style="font-weight: bold; text-align:right">2,603</td>
<td style="font-weight: bold; text-align:right">48,338</td>
<td style="font-weight: bold; text-align:right">1,263</td>
<td style="font-weight: bold; text-align:right">13,042,268</td>
<td style="font-weight: bold; text-align:right">254,247</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,297,612</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>21</td><td>792</td><td>4</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">2,450,068</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">56,832 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,174,625</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">218,611</td>
<td style="font-weight: bold; text-align:right">3,642</td>
<td style="font-weight: bold; text-align:right">53,832</td>
<td style="font-weight: bold; text-align:right">1,249</td>
<td style="font-weight: bold; text-align:right">9,266,106</td>

In [29]:
tags = table_code.find_all('tr')[1:]
tags

[<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>36,453,244</td>
 <td>+6,115</td>
 <td>830,579</td>
 <td>+616</td>
 <td>28,198,785</td>
 <td>+4,055</td>
 <td>7,423,880</td>
 <td>15,950</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>21,956,794</td>
 <td>+1,076</td>
 <td>577,701</td>
 <td>+19</td>
 <td>19,677,486</td>
 <td>+1,025</td>
 <td>1,701,607</td>
 <td>21,618</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>30,071,247</td>
 <td>+14,633</td>
 <td>440,142</td>
 <td>+159</td>
 <td>27,068,100</td>
 <td>+9,981</td>
 <td>2,563,005</td>
 <td>27,196</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>40,855,991</td>
 <td>+35,854</td>
 <td>937,594</td>
 <td>+855</td>
 <td>28,979,600</td>
 <td>+28,755</td>
 <td>10,938,797</td>
 <td>32,879</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>4,336,627</td>
 <td></td>
 <td>114,877</td>
 <td></td>
 <td>3,885,966</td>
 <td></td>
 <td>335,784</td>
 <td>3,240</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>58,861</td>
 <td>+35</td>
 <td>1,151</td>
 <td>+1</td>
 <td>34,640</td>
 <td>+12</td>
 <td>23,070</td>
 <td>5</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>133,733,485</td>
 <td>+57,713</td>
 <td>2,902,059</td>
 <td>+1,650</td>
 <td>107,845,283</td>
 <td>+43,828</td>
 <td>22,986,143</td>
 <td>100,888</td>
 <td>17,157</td>
 <td>372.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">31,637,243</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">572,849 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">24,206,539</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">6,857,855</td>
 <td style="font-weight: bold; text-align:right">9,058</td>
 <td style="font-weight: bold; text-align:right">95,153</td>
 <td style="font-weight: bold; text-align:right">1,723</td>
 <td style="font-weight: bold; text-align:right">413,478,674</td>
 <td style="font-weight: bold; text-align:right">1,243,583</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,489,703</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>11</td><td>580</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">13,197,031</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">341,097 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">11,664,158</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,191,776</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">61,750</td>
 <td style="font-weight: bold; text-align:right">1,596</td>
 <td style="font-weight: bold; text-align:right">28,600,000</td>
 <td style="font-weight: bold; text-align:right">133,822</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,716,460</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>16</td><td>627</td><td>7</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">12,928,574</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,513</td>
 <td style="font-weight: bold; text-align:right;">166,892 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">11,851,393</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,488</td>
 <td style="text-align:right;font-weight:bold;">910,289</td>
 <td style="font-weight: bold; text-align:right">8,944</td>
 <td style="font-weight: bold; text-align:right">9,299</td>
 <td style="font-weight: bold; text-align:right">120</td>
 <td style="font-weight: bold; text-align:right">252,677,379</td>
 <td style="font-weight: bold; text-align:right">181,732</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,390,382,831</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>108</td><td>8,331</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">4,841,308</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">97,722 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">301,299</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">4,442,287</td>
 <td style="font-weight: bold; text-align:right">5,626</td>
 <td style="font-weight: bold; text-align:right">74,044</td>
 <td style="font-weight: bold; text-align:right">1,495</td>
 <td style="font-weight: bold; text-align:right">67,791,157</td>
 <td style="font-weight: bold; text-align:right">1,036,811</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,384,318</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>14</td><td>669</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">4,606,162</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">101,480 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">4,229,480</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">275,202</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">31,553</td>
 <td style="font-weight: bold; text-align:right">695</td>
 <td style="font-weight: bold; text-align:right">122,300,000</td>
 <td style="font-weight: bold; text-align:right">837,772</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,982,499</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>32</td><td>1,439</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">4,367,291</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">126,927 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,932,777</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">307,587</td>
 <td style="font-weight: bold; text-align:right">469</td>
 <td style="font-weight: bold; text-align:right">64,075</td>
 <td style="font-weight: bold; text-align:right">1,862</td>
 <td style="font-weight: bold; text-align:right">132,141,580</td>
 <td style="font-weight: bold; text-align:right">1,938,717</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,159,282</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>16</td><td>537</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">3,700,393</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">112,374 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,040,182</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">547,837</td>
 <td style="font-weight: bold; text-align:right">3,683</td>
 <td style="font-weight: bold; text-align:right">61,271</td>
 <td style="font-weight: bold; text-align:right">1,861</td>
 <td style="font-weight: bold; text-align:right">51,755,739</td>
 <td style="font-weight: bold; text-align:right">856,975</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,393,531</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>16</td><td>537</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">3,633,925</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">32,943 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,194,978</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">406,004</td>
 <td style="font-weight: bold; text-align:right">2,604</td>
 <td style="font-weight: bold; text-align:right">42,735</td>
 <td style="font-weight: bold; text-align:right">387</td>
 <td style="font-weight: bold; text-align:right">40,385,250</td>
 <td style="font-weight: bold; text-align:right">474,936</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,033,013</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>23</td><td>2,581</td><td>2</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">3,326,736</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">76,037 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,085,059</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">165,640</td>
 <td style="font-weight: bold; text-align:right">2,009</td>
 <td style="font-weight: bold; text-align:right">71,132</td>
 <td style="font-weight: bold; text-align:right">1,626</td>
 <td style="font-weight: bold; text-align:right">43,458,915</td>
 <td style="font-weight: bold; text-align:right">929,231</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,768,680</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>14</td><td>615</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">2,927,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">78,174 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,631,400</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+16,900</td>
 <td style="text-align:right;font-weight:bold;">217,998</td>
 <td style="font-weight: bold; text-align:right">4,439</td>
 <td style="font-weight: bold; text-align:right">34,856</td>
 <td style="font-weight: bold; text-align:right">931</td>
 <td style="font-weight: bold; text-align:right">51,559,277</td>
 <td style="font-weight: bold; text-align:right">613,878</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,989,395</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>29</td><td>1,074</td><td>2</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
 <td style="font-weight: bold; text-align:right">2,479,617</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">64,767 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,345,471</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">69,379</td>
 <td style="font-weight: bold; text-align:right">2,603</td>
 <td style="font-weight: bold; text-align:right">48,338</td>
 <td style="font-weight: bold; text-align:right">1,263</td>
 <td style="font-weight: bold; text-align:right">13,042,268</td>
 <td style="font-weight: bold; text-align:right">254,247</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,297,612</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>21</td><td>792</td><td>4</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/poland/">Poland</a></td>
 <td style="font-weight: bold; text-align:right">2,471,617</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">55,703 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,054,697</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">361,217</td>
 <td style="font-weight: bold; text-align:right">3,342</td>
 <td style="font-weight: bold; text-align:right">65,361</td>
 <td style="font-weight: bold; text-align:right">1,473</td>
 <td style="font-weight: bold; text-align:right">12,588,747</td>
 <td style="font-weight: bold; text-align:right">332,906</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/poland-population/">37,814,773</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>15</td><td>679</td><td>3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
 <td style="font-weight: bold; text-align:right">2,450,068</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">56,832 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,174,625</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">218,611</td>
 <td style="font-weight: bold; text-align:right">3,642</td>
 <td style="font-weight: bold; text-align:right">53,832</td>
 <td style="font-weight: bold; text-align:right">1,249</td>
 <td style="font-weight: bold; text-align:right">9,266,106</td>
 <td style="font-weight: bold; text-align:right">203,592</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,513,099</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>19</td><td>801</td><td>5</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
 <td style="font-weight: bold; text-align:right">2,261,879</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,499</td>
 <td style="font-weight: bold; text-align:right;">205,598 </td>

In [61]:
tags[1].text.split('\n')

['',
 '',
 '',
 'South America',
 '',
 '21,956,794',
 '+1,076',
 '577,701',
 '+19',
 '19,677,486',
 '+1,025',
 '1,701,607',
 '21,618',
 '',
 '',
 '',
 '',
 '',
 'South America',
 '',
 '',
 '',
 '',
 '']

In [48]:
output = []
for i in tags:
    x = (i.text).split('\n')[2:-1]
    output.append(x)
print(output)

[['', 'North America', '', '36,453,244', '+6,115', '830,579', '+616', '28,198,785', '+4,055', '7,423,880', '15,950', '', '', '', '', '', 'North America', '', '', '', ''], ['', 'South America', '', '21,956,794', '+1,076', '577,701', '+19', '19,677,486', '+1,025', '1,701,607', '21,618', '', '', '', '', '', 'South America', '', '', '', ''], ['', 'Asia', '', '30,071,247', '+14,633', '440,142', '+159', '27,068,100', '+9,981', '2,563,005', '27,196', '', '', '', '', '', 'Asia', '', '', '', ''], ['', 'Europe', '', '40,855,991', '+35,854', '937,594', '+855', '28,979,600', '+28,755', '10,938,797', '32,879', '', '', '', '', '', 'Europe', '', '', '', ''], ['', 'Africa', '', '4,336,627', '', '114,877', '', '3,885,966', '', '335,784', '3,240', '', '', '', '', '', 'Africa', '', '', '', ''], ['', 'Oceania', '', '58,861', '+35', '1,151', '+1', '34,640', '+12', '23,070', '5', '', '', '', '', '', 'Australia/Oceania', '', '', '', ''], ['', '', '', '721', '', '15', '', '706', '', '0', '0', '', '', '', '', '', '', '', '', '', ''], ['World', '133,733,485', '+57,713', '2,902,059', '+1,650', '107,845,283', '+43,828', '22,986,143', '100,888', '17,157', '372.3', '', '', '', 'All', '', '', '', ''], ['USA', '31,637,243', '', '572,849 ', '', '24,206,539', '', '6,857,855', '9,058', '95,153', '1,723', '413,478,674', '1,243,583', '332,489,703 ', 'North America', '115801'], ['Brazil', '13,197,031', '', '341,097 ', '', '11,664,158', '', '1,191,776', '8,318', '61,750', '1,596', '28,600,000', '133,822', '213,716,460 ', 'South America', '166277'], ['India', '12,928,574', '+2,513', '166,892 ', '', '11,851,393', '+2,488', '910,289', '8,944', '9,299', '120', '252,677,379', '181,732', '1,390,382,831 ', 'Asia', '1088,3316'], ['France', '4,841,308', '', '97,722 ', '', '301,299', '', '4,442,287', '5,626', '74,044', '1,495', '67,791,157', '1,036,811', '65,384,318 ', 'Europe', '146691'], ['Russia', '4,606,162', '', '101,480 ', '', '4,229,480', '', '275,202', '2,300', '31,553', '695', '122,300,000', '837,772', '145,982,499 ', 'Europe', '321,4391'], ['UK', '4,367,291', '', '126,927 ', '', '3,932,777', '', '307,587', '469', '64,075', '1,862', '132,141,580', '1,938,717', '68,159,282 ', 'Europe', '165371'], ['Italy', '3,700,393', '', '112,374 ', '', '3,040,182', '', '547,837', '3,683', '61,271', '1,861', '51,755,739', '856,975', '60,393,531 ', 'Europe', '165371'], ['Turkey', '3,633,925', '', '32,943 ', '', '3,194,978', '', '406,004', '2,604', '42,735', '387', '40,385,250', '474,936', '85,033,013 ', 'Asia', '232,5812'], ['Spain', '3,326,736', '', '76,037 ', '', '3,085,059', '', '165,640', '2,009', '71,132', '1,626', '43,458,915', '929,231', '46,768,680 ', 'Europe', '146151'], ['Germany', '2,927,572', '', '78,174 ', '', '2,631,400', '+16,900', '217,998', '4,439', '34,856', '931', '51,559,277', '613,878', '83,989,395 ', 'Europe', '291,0742'], ['Colombia', '2,479,617', '', '64,767 ', '', '2,345,471', '', '69,379', '2,603', '48,338', '1,263', '13,042,268', '254,247', '51,297,612 ', 'South America', '217924'], ['Poland', '2,471,617', '', '55,703 ', '', '2,054,697', '', '361,217', '3,342', '65,361', '1,473', '12,588,747', '332,906', '37,814,773 ', 'Europe', '156793'], ['Argentina', '2,450,068', '', '56,832 ', '', '2,174,625', '', '218,611', '3,642', '53,832', '1,249', '9,266,106', '203,592', '45,513,099 ', 'South America', '198015'], ['Mexico', '2,261,879', '+5,499', '205,598 ', '+596', '1,798,657', '+3,444', '257,624', '4,798', '17,403', '1,582', '6,191,679', '47,640', '129,968,675 ', 'North America', '5763221'], ['Iran', '1,984,348', '', '63,699 ', '', '1,675,891', '', '244,758', '4,177', '23,396', '751', '13,331,229', '157,181', '84,814,315 ', 'Asia', '431,3316'], ['Ukraine', '1,803,998', '+19,419', '35,962 ', '+464', '1,383,883', '+10,032', '384,153', '177', '41,441', '826', '8,456,635', '194,264', '43,531,619 ', 'Europe', '241,2105'], ['Peru', '1,607,898', '', '53,725 ', '', '1,527,112', '', '27,061', '2,249', '48,252', '1,612', '9,709,043', '291,365', '33,322,600 ', 'South America', '216203'], ['Czechia', '1,567,848', '+7,015', '27,466 ', '+56', '1,434,281', '+339', '106,101', '1,349', '146,197', '2,561', '13,812,844', '1,288,004', '10,724,225 ', 'Europe', '73901'], ['South Africa', '1,553,609', '', '53,111 ', '', '1,479,821', '', '20,677', '546', '25,945', '887', '10,020,025', '167,335', '59,880,039 ', 'Africa', '391,1276'], ['Indonesia', '1,547,376', '', '42,064 ', '', '1,391,742', '', '113,570', '', '5,612', '153', '13,134,650', '47,635', '275,735,418 ', 'Asia', '1786,55521'], ['Netherlands', '1,319,353', '', '16,672 ', '', 'N/A', 'N/A', 'N/A', '765', '76,868', '971', '10,795,845', '628,983', '17,163,958 ', 'Europe', '131,0302'], ['Chile', '1,043,022', '', '23,796 ', '', '980,245', '', '38,981', '3,029', '54,206', '1,237', '11,603,698', '603,047', '19,241,784 ', 'South America', '188092'], ['Canada', '1,028,041', '', '23,173 ', '', '942,732', '', '62,136', '835', '27,057', '610', '28,455,431', '748,918', '37,995,393 ', 'North America', '371,6401'], ['Romania', '988,624', '', '24,561 ', '', '885,710', '', '78,353', '1,487', '51,655', '1,283', '7,550,873', '394,529', '19,138,936 ', 'Europe', '197793'], ['Belgium', '908,212', '+3,539', '23,301 ', '+54', '58,568', '+110', '826,343', '898', '78,104', '2,004', '11,511,956', '989,996', '11,628,288 ', 'Europe', '134991'], ['Iraq', '895,622', '', '14,572 ', '', '794,444', '', '86,606', '491', '21,893', '356', '8,331,013', '203,646', '40,909,209 ', 'Asia', '462,8075'], ['Sweden', '841,807', '', '13,578 ', '', 'N/A', 'N/A', 'N/A', '356', '82,957', '1,338', '7,530,772', '742,130', '10,147,504 ', 'Europe', '127471'], ['Israel', '835,216', '', '6,266 ', '', '824,160', '', '4,790', '294', '90,808', '681', '13,632,392', '1,482,170', '9,197,590 ', 'Asia', '111,4681'], ['Portugal', '825,031', '', '16,890 ', '', '782,294', '', '25,847', '116', '81,093', '1,660', '9,291,032', '913,226', '10,173,859 ', 'Europe', '126021'], ['Philippines', '819,164', '', '14,059 ', '', '646,404', '', '158,701', '785', '7,400', '127', '10,515,678', '94,997', '110,695,150 ', 'Asia', '1357,87411'], ['Pakistan', '705,517', '+5,329', '15,124 ', '+98', '623,399', '+2,610', '66,994', '3,942', '3,147', '67', '10,584,877', '47,220', '224,159,995 ', 'Asia', '31814,82121'], ['Hungary', '698,490', '+4,814', '22,681 ', '+272', '419,765', '+613', '256,044', '1,337', '72,446', '2,352', '4,825,607', '500,504', '9,641,501 ', 'Europe', '144252'], ['Bangladesh', '659,278', '', '9,447 ', '', '561,639', '', '88,192', '', '3,973', '57', '4,882,565', '29,423', '165,944,401 ', 'Asia', '25217,56634'], ['Jordan', '650,681', '', '7,469 ', '', '570,327', '', '72,885', '729', '63,292', '727', '6,198,917', '602,972', '10,280,612 ', 'Asia', '161,3762'], ['Serbia', '629,388', '', '5,579 ', '', '536,672', '', '87,137', '267', '72,258', '641', '3,531,777', '405,471', '8,710,312 ', 'Europe', '141,5612'], ['Switzerland', '612,575', '', '10,432 ', '', '554,729', '', '47,414', '186', '70,386', '1,199', '6,260,306', '719,320', '8,703,085 ', 'Europe', '148341'], ['Austria', '566,008', '', '9,546 ', '', '522,774', '', '33,688', '581', '62,572', '1,055', '25,515,997', '2,820,765', '9,045,771 ', 'Europe', '169480'], ['Morocco', '499,688', '', '8,867 ', '', '486,349', '', '4,472', '251', '13,416', '238', '6,051,185', '162,470', '37,244,942 ', 'Africa', '754,2006'], ['Japan', '489,576', '', '9,279 ', '', '455,382', '', '24,915', '456', '3,880', '74', '10,185,014', '80,719', '126,178,877 ', 'Asia', '25813,59812'], ['Lebanon', '485,918', '', '6,512 ', '', '391,197', '', '88,209', '875', '71,438', '957', '3,632,919', '534,100', '6,801,941 ', 'Asia', '141,0452'], ['UAE', '476,019', '', '1,520 ', '', '460,841', '', '13,658', '', '47,689', '152', '39,287,609', '3,935,953', '9,981,727 ', 'Asia', '216,5670'], ['Saudi Arabia', '394,952', '', '6,719 ', '', '381,189', '', '7,044', '852', '11,211', '191', '15,533,915', '440,958', '35,227,614 ', 'Asia', '895,2432'], ['Slovakia', '366,894', '', '10,243 ', '', '255,300', '', '101,351', '584', '67,176', '1,875', '2,399,863', '439,401', '5,461,672 ', 'Europe', '155332'], ['Bulgaria', '364,419', '', '14,034 ', '', '278,665', '', '71,720', '777', '52,752', '2,032', '2,224,530', '322,014', '6,908,183 ', 'Europe', '194923'], ['Panama', '357,277', '', '6,148 ', '', '346,611', '', '4,518', '105', '81,820', '1,408', '2,205,603', '505,108', '4,366,596 ', 'North America', '127102'], ['Malaysia', '354,468', '', '1,304 ', '', '339,067', '', '14,097', '194', '10,846', '40', '7,992,575', '244,550', '32,682,822 ', 'Asia', '9225,0644'], ['Ecuador', '339,604', '', '17,057 ', '', '290,314', '', '32,233', '576', '19,028', '956', '1,172,622', '65,702', '17,847,533 ', 'South America', '531,04615'], ['Belarus', '330,536', '', '2,314 ', '', '320,844', '', '7,378', '', '34,989', '245', '5,478,163', '579,888', '9,446,936 ', 'Europe', '294,0832'], ['Georgia', '286,406', '+761', '3,849 ', '+9', '276,084', '+537', '6,473', '', '71,902', '966', '3,584,251', '899,823', '3,983,284 ', 'Asia', '141,0351'], ['Greece', '285,015', '', '8,607 ', '', '240,926', '', '35,482', '749', '27,448', '829', '6,878,215', '662,392', '10,383,899 ', 'Europe', '361,2062'], ['Croatia', '282,548', '', '6,149 ', '', '265,038', '', '11,361', '160', '69,154', '1,505', '1,599,453', '391,467', '4,085,789 ', 'Europe', '146643'], ['Nepal', '278,768', '', '3,038 ', '', '273,529', '', '2,201', '', '9,438', '103', '2,298,167', '77,808', '29,536,306 ', 'Asia', '1069,72213'], ['Bolivia', '277,966', '+1,076', '12,385 ', '+19', '227,812', '+1,025', '37,769', '71', '23,567', '1,050', '954,381', '80,917', '11,794,631 ', 'South America', '4295212'], ['Azerbaijan', '276,464', '', '3,780 ', '', '244,540', '', '28,144', '', '27,080', '370', '2,963,012', '290,232', '10,209,107 ', 'Asia', '372,7013'], ['Tunisia', '264,994', '', '9,087 ', '', '221,545', '', '34,362', '382', '22,244', '763', '1,153,654', '96,838', '11,913,192 ', 'Africa', '451,31110'], ['Kazakhstan', '261,503', '+2,586', '3,171 ', '+15', '229,538', '+1,449', '28,794', '221', '13,801', '167', '8,994,537', '474,687', '18,948,360 ', 'Asia', '725,9762'], ['Palestine', '259,133', '', '2,753 ', '', '226,090', '', '30,290', '203', '49,914', '530', '1,605,666', '309,281', '5,191,607 ', 'Asia', '201,8863'], ['Dominican Republic', '254,937', '', '3,369 ', '', '214,943', '', '36,625', '157', '23,322', '308', '1,325,145', '121,227', '10,931,116 ', 'North America', '433,2458'], ['Kuwait', '241,469', '', '1,379 ', '', '226,026', '', '14,064', '207', '55,911', '319', '2,121,475', '491,220', '4,318,784 ', 'Asia', '183,1322'], ['Ireland', '239,325', '', '4,732 ', '', '23,364', '', '211,229', '60', '48,058', '950', '4,117,128', '826,740', '4,979,955 ', 'Europe', '211,0521'], ['Moldova', '237,718', '', '5,268 ', '', '218,711', '', '13,739', '316', '59,035', '1,308', '881,765', '218,976', '4,026,759 ', 'Europe', '177645'], ['Denmark', '234,931', '', '2,435 ', '', '223,824', '', '8,672', '34', '40,451', '419', '27,555,084', '4,744,461', '5,807,843 ', 'Europe', '252,3850'], ['Paraguay', '227,116', '', '4,584 ', '', '186,730', '', '35,802', '436', '31,546', '637', '951,218', '132,123', '7,199,490 ', 'South America', '321,5718'], ['Lithuania', '223,127', '+1,067', '3,647 ', '+9', '203,803', '+761', '15,677', '161', '82,855', '1,354', '2,446,061', '908,306', '2,692,991 ', 'Europe', '127381'], ['Slovenia', '221,890', '', '4,092 ', '', '204,497', '', '13,301', '131', '106,721', '1,968', '1,085,708', '522,187', '2,079,157 ', 'Europe', '95082'], ['Ethiopia', '221,544', '', '3,058 ', '', '166,135', '', '52,351', '906', '1,891', '26', '2,414,973', '20,618', '117,127,909 ', 'Africa', '52938,30249'], ['Costa Rica', '219,846', '', '3,000 ', '', '193,857', '', '22,989', '194', '42,857', '585', '842,015', '164,145', '5,129,711 ', 'North America', '231,7106'], ['Egypt', '207,293', '', '12,290 ', '', '157,450', '', '37,553', '90', '1,997', '118', '2,507,491', '24,156', '103,805,216 ', 'Africa', '5018,44641'], ['Armenia', '200,129', '+1,231', '3,675 ', '+28', '179,043', '+816', '17,411', '', '67,440', '1,238', '889,872', '299,873', '2,967,493 ', 'Asia', '158073'], ['Guatemala', '198,374', '', '6,928 ', '', '182,408', '', '9,038', '5', '10,919', '381', '1,077,904', '59,329', '18,168,150 ', 'North America', '922,62217'], ['Honduras', '193,029', '+616', '4,703 ', '+17', '74,299', '+611', '114,027', '512', '19,255', '469', '531,255', '52,994', '10,024,803 ', 'North America', '522,13219'], ['Qatar', '186,201', '', '320 ', '', '167,480', '', '18,401', '427', '66,316', '114', '1,780,877', '634,260', '2,807,805 ', 'Asia', '158,7742'], ['Bosnia and Herzegovina', '179,248', '', '7,132 ', '', '137,242', '', '34,874', '', '54,898', '2,184', '824,150', '252,410', '3,265,118 ', 'Europe', '184584'], ['Venezuela', '170,189', '', '1,705 ', '', '154,023', '', '14,461', '237', '5,998', '60', '3,359,014', '118,383', '28,374,019 ', 'South America', '16716,6428'], ['Oman', '166,685', '', '1,735 ', '', '149,049', '', '15,901', '204', '32,022', '333', '1,550,000', '297,773', '5,205,306 ', 'Asia', '313,0003'], ['Libya', '165,287', '', '2,772 ', '', '151,189', '', '11,326', '', '23,807', '399', '896,128', '129,076', '6,942,655 ', 'Africa', '422,5058'], ['Nigeria', '163,498', '', '2,058 ', '', '153,788', '', '7,652', '11', '778', '10', '1,803,177', '8,586', '210,022,724 ', 'Africa', '1,285102,052116'], ['Bahrain', '151,931', '', '547 ', '', '141,119', '', '10,265', '74', '87,000', '313', '3,704,727', '2,121,443', '1,746,324 ', 'Asia', '113,1930'], ['Myanmar', '142,541', '', '3,206 ', '', '131,829', '', '7,506', '', '2,606', '59', '2,546,239', '46,558', '54,689,159 ', 'Asia', '38417,05821'], ['Kenya', '141,365', '', '2,276 ', '', '97,194', '', '41,895', '236', '2,586', '42', '1,530,736', '27,998', '54,672,609 ', 'Africa', '38724,02136'], ['North Macedonia', '137,728', '', '4,073 ', '', '111,765', '', '21,890', '124', '66,110', '1,955', '651,997', '312,962', '2,083,308 ', 'Europe', '155113'], ['Albania', '127,192', '', '2,291 ', '', '95,600', '', '29,301', '18', '44,235', '797', '573,313', '199,387', '2,875,383 ', 'Europe', '231,2555'], ['Uruguay', '126,987', '', '1,231 ', '', '98,837', '', '26,919', '436', '36,459', '353', '1,470,153', '422,099', '3,482,961 ', 'South America', '272,8292'], ['Algeria', '118,004', '', '3,116 ', '', '82,192', '', '32,696', '19', '2,654', '70', '230,861', '5,193', '44,454,659 ', 'Africa', '37714,267193'], ['Estonia', '111,664', '', '976 ', '', '90,551', '', '20,137', '70', '84,134', '735', '1,176,690', '886,582', '1,327,220 ', 'Europe', '121,3601'], ['S. Korea', '107,598', '+700', '1,758 ', '+2', '98,360', '+432', '7,480', '112', '2,097', '34', '8,012,421', '156,178', '51,303,051 ', 'Asia', '47729,1836'], ['Latvia', '105,176', '', '1,946 ', '', '96,254', '', '6,976', '77', '56,240', '1,041', '1,961,149', '1,048,671', '1,870,128 ', 'Europe', '189611'], ['Norway', '101,082', '', '683 ', '', '80,023', '', '20,376', '54', '18,535', '125', '4,768,101', '874,288', '5,453,693 ', 'Europe', '547,9851'], ['Sri Lanka', '93,910', '', '588 ', '', '90,917', '', '2,405', '', '4,372', '27', '2,374,627', '110,540', '21,482,078 ', 'Asia', '22936,5349'], ['Montenegro', '93,309', '', '1,334 ', '', '86,945', '', '5,030', '69', '148,551', '2,124', '346,734', '552,013', '628,127 ', 'Europe', '74712'], ['Ghana', '91,009', '', '752 ', '', '88,810', '', '1,447', '32', '2,883', '24', '1,016,808', '32,211', '31,566,766 ', 'Africa', '34741,97731'], ['Kyrgyzstan', '89,660', '+222', '1,516 ', '+4', '85,607', '+111', '2,537', '24', '13,572', '229', '886,816', '134,238', '6,606,303 ', 'Asia', '744,3587'], ['Zambia', '89,386', '', '1,224 ', '', '85,409', '', '2,753', '76', '4,761', '65', '1,280,670', '68,213', '18,774,694 ', 'Africa', '21015,33915'], ['Uzbekistan', '84,322', '+195', '634 ', '+1', '82,234', '+179', '1,454', '23', '2,492', '19', '1,377,915', '40,719', '33,839,530 ', 'Asia', '40153,37525'], ['Cuba', '82,601', '', '442 ', '', '76,883', '', '5,276', '77', '7,296', '39', '3,129,044', '276,385', '11,321,307 ', 'North America', '13725,6144'], ['Finland', '80,416', '', '862 ', '', '46,000', '', '33,554', '45', '14,496', '155', '4,085,073', '736,404', '5,547,325 ', 'Europe', '696,4351'], ['Mozambique', '68,431', '', '785 ', '', '58,063', '', '9,583', '68', '2,144', '25', '491,304', '15,392', '31,920,002 ', 'Africa', '46640,66265'], ['El Salvador', '65,491', '', '2,040 ', '+3', '62,340', '', '1,111', '30', '10,058', '313', '856,658', '131,565', '6,511,286 ', 'North America', '993,1928'], ['Luxembourg', '62,793', '', '762 ', '', '58,544', '', '3,487', '30', '99,082', '1,202', '2,464,563', '3,888,875', '633,747 ', 'Europe', '108320'], ['Singapore', '60,554', '', '30 ', '', '60,260', '', '264', '1', '10,289', '5', '8,789,647', '1,493,425', '5,885,565 ', 'Asia', '97196,1861'], ['Cameroon', '57,337', '', '851 ', '', '51,769', '', '4,717', '53', '2,120', '31', '1,187,367', '43,898', '27,048,056 ', 'Africa', '47231,78423'], ['Afghanistan', '56,943', '', '2,516 ', '', '51,940', '', '2,487', '1,120', '1,438', '64', '361,494', '9,130', '39,595,345 ', 'Asia', '69515,737110'], ['Cyprus', '49,366', '', '266 ', '', '2,057', '', '47,043', '48', '40,661', '219', '3,559,362', '2,931,714', '1,214,089 ', 'Asia', '254,5640'], ['Namibia', '45,039', '', '548 ', '', '43,306', '', '1,185', '32', '17,484', '213', '355,501', '138,006', '2,575,982 ', 'Africa', '574,7017'], ['Ivory Coast', '44,880', '', '257 ', '', '43,446', '', '1,177', '', '1,670', '10', '541,414', '20,146', '26,874,731 ', 'Africa', '599104,57150'], ['Botswana', '41,710', '', '616 ', '', '36,958', '', '4,136', '1', '17,468', '258', '942,561', '394,742', '2,387,788 ', 'Africa', '573,8763'], ['Jamaica', '41,400', '', '631 ', '', '18,444', '', '22,325', '33', '13,934', '212', '294,789', '99,220', '2,971,075 ', 'North America', '724,70910'], ['Uganda', '41,046', '', '337 ', '', '40,685', '', '24', '', '876', '7', '955,609', '20,404', '46,835,531 ', 'Africa', '1,141138,97849'], ['Senegal', '39,164', '', '1,070 ', '', '37,888', '', '206', '25', '2,293', '63', '448,014', '26,232', '17,079,046 ', 'Africa', '43615,96238'], ['Zimbabwe', '36,984', '', '1,531 ', '', '34,803', '', '650', '3', '2,461', '102', '390,833', '26,007', '15,028,105 ', 'Africa', '4069,81638'], ['Malawi', '33,718', '', '1,125 ', '', '30,996', '', '1,597', '23', '1,729', '58', '221,473', '11,354', '19,505,475 ', 'Africa', '57817,33888'], ['Thailand', '30,310', '+405', '95 ', '', '28,101', '+32', '2,114', '1', '433', '1', '8,124,896', '116,179', '69,934,331 ', 'Asia', '2,307736,1519'], ['Sudan', '30,111', '', '2,063 ', '', '24,214', '', '3,834', '', '675', '46', '232,965', '5,220', '44,627,885 ', 'Africa', '1,48221,633192'], ['Malta', '29,408', '', '400 ', '', '28,463', '', '545', '', '66,467', '904', '824,234', '1,862,907', '442,445 ', 'Europe', '151,1061'], ['Australia', '29,382', '+5', '909 ', '', '26,326', '+2', '2,147', '', '1,142', '35', '15,976,923', '621,041', '25,726,041 ', 'Australia/Oceania', '87628,3012'], ['DRC', '28,410', '', '745 ', '', '25,841', '', '1,824', '', '310', '8', '142,542', '1,556', '91,625,594 ', 'Africa', '3,225122,987643'], ['Madagascar', '26,127', '', '469 ', '', '22,947', '', '2,711', '246', '925', '17', '148,563', '5,262', '28,231,842 ', 'Africa', '1,08160,196190'], ['Maldives', '25,191', '', '67 ', '', '22,014', '', '3,110', '88', '45,986', '122', '659,127', '1,203,219', '547,803 ', 'Asia', '228,1761'], ['Rwanda', '23,041', '', '314 ', '', '20,835', '', '1,892', '5', '1,746', '24', '1,194,484', '90,517', '13,196,240 ', 'Africa', '57342,02611'], ['Angola', '23,010', '', '547 ', '', '21,545', '', '918', '13', '684', '16', '430,968', '12,811', '33,641,078 ', 'Africa', '1,46261,50178'], ['Guinea', '20,554', '', '131 ', '', '18,302', '', '2,121', '24', '1,534', '10', '410,711', '30,643', '13,403,249 ', 'Africa', '652102,31533'], ['Gabon', '20,265', '', '124 ', '', '17,227', '', '2,914', '25', '8,944', '55', '654,156', '288,725', '2,265,671 ', 'Africa', '11218,2723'], ['Syria', '19,761', '', '1,342 ', '', 

In [49]:
import csv
file = open('worldometer.csv','w')
x = csv.writer(file)
for i in output:
    x.writerow(i)
file.close()

In [2]:
import pandas as pd 
df = pd.read_csv('worldometer.csv' ,'latin-1')
df.head(20)

<ipython-input-2-d7d05aa262de>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('worldometer.csv' ,'latin-1')

   ,North America,,"36,453,244","+6,115","830,579",+616,"28,198,785","+4,055","7,423,880","15,950",,,,,,North America,,,,
0   ,South America,,"21,956,794","+1,076","577,701...
1   ,Asia,,"30,071,247","+14,633","440,142",+159,"...
2   ,Europe,,"40,855,991","+35,854","937,594",+855...
3   ,Africa,,"4,336,627",,"114,877",,"3,885,966",,...
4   ,Oceania,,"58,861",+35,"1,151",+1,"34,640",+12...
5                      ,,,721,,15,,706,,0,0,,,,,,,,,,
6   World,"133,733,485","+57,713","2,902,059","+1,...
7   USA,"31,637,243",,"572,849 ",,"24,206,539",,"6...
8   Brazil,"13,197,031",,"341,097 ",,"11,664,158",...
9   India,"12,928,574","+2,513","166,892 ",,"11,85...
10  France,"4,841,308",,"97,722 ",,"301,299",,"4,4...
11  Russia,"4,606,162",,"101,480 ",,"4,229,480",,"...
12  UK,"4,367,291",,"126,927 ",,"3,932,777",,"307,...
13  Italy,"3,700,393",,"112,374 ",,"3,040,182",,"5...
14  Turkey,"3,633,925",,"32,943 ",,"3,194,978",,"4...
15  Spain,"3,326,736",,"76,037 ",,"3,085,059",,"16...
16  Germany,"2,927,572",,"78,174 ",,"2,631,400","+...
17  Colombia,"2,479,617",,"64,767 ",,"2,345,471",,...
18  Poland,"2,471,617",,"55,703 ",,"2,054,697",,"3...
19  Argentina,"2,450,068",,"56,832 ",,"2,174,625",...